### ISSUE TITLE
Cambiamento repository

### ISSUE THREAD

**Issue by stefa168** [tsi-unito/guida_degli_studenti_di#63]
### Discussed in https://github.com/stefa168/guida_degli_studenti_di/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **federicotorrielli** October 24, 2022</sup>
Propongo, come abbiamo fatto per tutte le altre repo, di portare questa sul TSI.</div>

**Comment by stefa168** [comment]
Precedentemente scritto da @federicotorrielli:

@TheTipo01 quando hai tempo scrivi qua un piano per il git lfs, se volete possiamo ancora usare i soldi del torrent per prendere un server esterno.

**Comment by stefa168** [comment]
### Organization

Ci sta spostare sotto l'organization, l'unica cosa è che perdiamo le star e i watchers... 😢

Per il resto non c'è problema a forkare, fare un commit finale qui cancellando tutto e mettendo un messaggio enorme che invita a spostarsi sul nuovo repo. Infine archiviamo e via

### Server esterno

Onestamente se possibile terrei tutto su github, per lo più perché non so come possiamo lavorare spostando sotto l'organization, o se ad esempio la gente vuole fare PR

**Comment by TheTipo01** [comment]
> Precedentemente scritto da @federicotorrielli:
> 
> @TheTipo01 quando hai tempo scrivi qua un piano per il git lfs, se volete possiamo ancora usare i soldi del torrent per prendere un server esterno.

Provo a fare delle prove in locale su repo private per capire di più riguardo i costi su github dell'LFS, se no uniamo i commit che duplicano i blob per risparmiare spazio

**Comment by federicotorrielli** [comment]
> > Precedentemente scritto da @federicotorrielli:
> > @TheTipo01 quando hai tempo scrivi qua un piano per il git lfs, se volete possiamo ancora usare i soldi del torrent per prendere un server esterno.
> 
> Provo a fare delle prove in locale su repo private per capire di più riguardo i costi su github dell'LFS, se no uniamo i commit che duplicano i blob per risparmiare spazio

![好的，我等](https://media.tenor.com/VKs-TWiBLmEAAAAd/john-cena.gif)

**Comment by stefa168** [comment]
Parlando l'altro giorno con @TheTipo01 abbiamo visto che si può migrare un repository sotto un'organizzazione; in questi giorni faccio un paio di prove!
