### ISSUE TITLE
Contribuzione ad una materia già trattata

### ISSUE THREAD

**Issue by EmanueleSpadaro** [tsi-unito/guida_degli_studenti_di#98]
Ciao,
vorrei contribuire con i miei appunti di SISINT, ma non saprei come comportarmi perché all'interno della repository ci sono già alcuni appunti

**Comment by TheTipo01** [comment]
Quello che facciamo in genere è muovere gli appunti già esistenti in una nuova cartella con il nome di chi l'ha scritti
Poi ne crei una per i tuoi e li butti li dentro

**Comment by EmanueleSpadaro** [comment]
La ringrazio signor Raimo
